CREATE TABLE [dbo].[ADMINISTRADOR_EVENTO]
(
	[ADMINEVENT_ID] INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
    [ADMINEVENT_USER_ID] INT NULL, 
    [ADMINEVENT_EVENT_ID] INT NULL, 
    [ADMINEVENT_FECHA] DATETIME NULL, 
    [ADMINEVENT_ESTADO] BIT NULL, 
    [ADMINEVENT_PRVILEGIOS] VARCHAR(50) NULL
)
