CREATE TABLE [dbo].[CANDIDATOS] (
  [CAN_IDS] INT NOT NULL PRIMARY KEY IDENTITY (1, 1),
  [CAN_INFORMACION_ADICIONAL] TEXT NULL,
  [CAN_ESTADO] BIT NULL,
  [CAN_EVT_ID] int null,
  [CAN_USU_ID] int null
)