CREATE TABLE [dbo].[CANDIDATO_IMAGENES]
(
  [CAN_IMG_ID] INT NOT NULL PRIMARY KEY IDENTITY (1, 1),
  [CAN_IMG_EVT_ID] INT NULL,
  [CAN_IMG_CAN_ID] INT NULL,
  [CAN_IMG_AMBIENTE] VARCHAR(50),
  [CAN_IMG_IMAGEN] VARCHAR (200)
)
