CREATE TABLE [dbo].[CANDIDATOS] (
  [CAN_IDS] INT NOT NULL PRIMARY KEY IDENTITY (1, 1),
  [CAN_IMAGEN] VARCHAR(50) NULL,
  [CAN_VIDEO] VARCHAR(50) NULL,
  [CAN_DETALLES] VARCHAR(50) NULL,
  [CAN_ROL] VARCHAR(50) NULL,
  [CAN_EDAD] INT NULL,
  [CAN_PROPUESTA] VARCHAR(50) NULL,
  [CAN_PUESTOS_LABORALES] VARCHAR(50) NULL,
  [CAN_ESTADO] BIT NULL,
  [CAN_EVT_ID] int null,
  [CAN_USU_ID] int null
)