CREATE TABLE [dbo].[EVENTOS]
(
	[ID_EVENTO ]	  INT      IDENTITY (1, 1) NOT NULL,
    [NOMBRE_EVENTO]		VARCHAR(50) NULL, 
    [FOTO_EVENTO] VARCHAR(50) NULL, 
    [DESCRIPCION_EVENTO] VARCHAR(50) NULL,
    [MAX_PERSONAS_EVENTO] BIT NULL, 
    [NUM_MAX_PERSONAS_EVENTO] INT NULL, 
    [NUM_MAX_CANDIDATOS_EVENTO] INT NULL, 
    [CATEGORIA] VARCHAR(50) NULL
)
