CREATE TABLE [dbo].[GRUPOS] (
  [GRP_ID] INT NOT NULL PRIMARY KEY IDENTITY (1, 1),
  [GRP_NOMBRE] VARCHAR(50) NULL,
  [GRP_DETALLES] TEXT NULL,
  [GRP_MAXIMO_CANDIDATOS] INT NULL,
  [GRP_FOTO] VARCHAR(50) NULL,
  [GRP_ESTADO] BIT NULL,
  [GRP_EVENTO_ID] INT NULL,
)