CREATE TABLE [dbo].[GRUPOS] (
  [ID_GRUPO] INT NOT NULL PRIMARY KEY IDENTITY (1, 1),
  [NOMBRE_GRUPO] VARCHAR(50) NULL,
  [DETALLES_GRUPO] TEXT NULL,
  [MAXIMO_CANDIDATOS_GRUPO] INT NULL,
  [FOTO_GRUPO] VARCHAR(50) NULL,
  [ESTADO_GRUPO] BIT NULL
)