CREATE TABLE [dbo].[USUARIOS] (
    [ID_USUARIO]       INT NOT NULL PRIMARY KEY  IDENTITY (1, 1),
    [CEDULA_USUARIO] VARCHAR(15) NULL,
    [NICK_USUARIO]   VARCHAR(30) NULL,
    [PASSWORD_USUARIO] VARCHAR(100) NULL, 
    [NOMBRE_USUARIO] VARCHAR(30) NULL, 
    [SEGUNDO_NOMBRE_USUARIO] VARCHAR(30) NULL, 
    [APELLIDO_USUARIO] VARCHAR(30) NULL, 
    [SEGUNDO_APELLIDO_USUARIO] VARCHAR(30) NULL, 
    [FECHA_NACIMIENTO_USUARIO] DATE NULL, 
    [CORREO_USUARIO] VARCHAR(50) NULL, 
    [ROL_USUARIO] INT NULL, 
    [NOMBRE_ROL_USUARIO] VARCHAR(30) NULL, 
    [ESTADO_USUARIO] BIT NULL
);
GO
CREATE INDEX [CONSTRAINT_CED_USUARIO] ON [dbo].[USUARIOS] (CEDULA_USUARIO)
