CREATE TABLE [dbo].[USUARIOS] (
    [USU_ID]   INT NOT NULL PRIMARY KEY  IDENTITY (1, 1),
    [USU_CEDULA] VARCHAR(15) NULL,
    [USU_NICK]   VARCHAR(30) NULL,
    [USU_PASSWORD] VARCHAR(100) NULL, 
    [USU_NOMBRE] VARCHAR(30) NULL, 
    [USU_SEGUNDO_NOMBRE] VARCHAR(30) NULL, 
    [USU_APELLIDO] VARCHAR(30) NULL, 
    [USU_SEGUNDO_APELLIDO] VARCHAR(30) NULL, 
    [USU_FECHA_NACIMIENTO] DATE NULL, 
    [USU_CORREO] VARCHAR(50) NULL, 
    [USU_ESTADO] BIT NULL,
    [USU_NUM_EVENT_MAX] int null DEFAULT 1
);
GO
CREATE INDEX [CONSTRAINT_CED_USUARIO] ON [dbo].[USUARIOS] (USU_CEDULA)
