CREATE TABLE [dbo].[VOTOS_REGISTRO_CORREO]
(
  [VRC_ID] INT NOT NULL PRIMARY KEY  IDENTITY (1, 1),
  [VRC_EVT_ID] INT NULL,
  [VRC_USU_CORREO] VARCHAR (100) NULL,
  [VRC_USU_ASIGNADOR_ID] INT NULL
 )
