CREATE TABLE [dbo].[VOTOS]
(
  [VTO_ID] INT NOT NULL PRIMARY KEY  IDENTITY (1, 1),
  [VTO_EVT_ID] INT NULL,
  [VTO_USU_ID] INT NULL,
  [VTO_GRP_ID] INT NULL,
  [VTO_FECHA] DATETIME NULL,
  [VTO_ESTADO] bit NULL,



)
