CREATE TABLE [dbo].[VOTOS]
(
  [VTO_ID] INT NOT NULL PRIMARY KEY  IDENTITY (1, 1),
  [VTO_EVT_ID] INT NULL,
  [VTO_USU_ID] INT NULL,
  [VTO_CAN_ID] INT NULL,
  [VTO_FECHA_INSCRIPCION] DATETIME NULL,
  [VTO_FECHA_VOTACION] DATETIME NULL,
  [VTO_REGISTRO] bit NULL,
  [VTO_ESTADO] bit NULL
)
