DELETE  FROM USUARIOS
DBCC CHECKIDENT (USUARIOS, RESEED, 1)
GO

DELETE  FROM CANDIDATOS
DBCC CHECKIDENT (CANDIDATOS, RESEED, 1)
GO

DELETE  FROM EVENTOS
DBCC CHECKIDENT (EVENTOS, RESEED, 1)
GO

DELETE  FROM ADMINISTRADOR_EVENTO
DBCC CHECKIDENT (ADMINISTRADOR_EVENTO, RESEED, 1)
GO

DELETE  FROM VOTOS
DBCC CHECKIDENT (VOTOS, RESEED, 1)
GO

DELETE  FROM VOTOS
DBCC CHECKIDENT (EVENTOS_CANTIDAD, RESEED, 1)
GO